### ISSUE TITLE
Security bug: Http header injection for X-Auth-Preferred-Username

### ISSUE THREAD

**Issue by gebinic** [Yeicor/traefikgothauth#16]
I have a nexus2 that uses RUT authentication and only needs the header “X-Auth-Preferred-Username” for a login. In front of it is a Traefik that uses this plugin. I logged in to the service with my username “gebinic” and after that I see my username in the user profile, so everything worked. Then I send a new request with the header “X-Auth-Preferred-Username”, but this time with a different username, e.g. “root”. This request is authenticated as user “root” and **not** as user “gebinic”, which means I see “root” in my user profile and also have the corresponding permissions.

I think a simple solution to this problem is to remove the “X-Auth-Preferred-Username” header from the incoming request, if present. Additional logging can also help to identify potential attackers. This solution must also take the “ClaimsPrefix” property into account.

**Comment by Yeicor** [comment]
You're right—thank you for reporting this! Previously, when a logged-in user sent a forged header, the middleware would add the correct header to the request but still send the user's fake one first.

This behavior has been fixed in v0.4.10. Now, the header is always overwritten, and the original contents are logged as a warning to help identify potential attackers.

I had planned to use this for my home lab but never found the time, so it didn’t receive sufficient security-related testing. I’ve added a note in the README to manage user expectations for now.
